version: '3'
services: 
  server:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:10.7-alpine
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
